name: admin_multivendor_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # firebase
  firebase_auth: any
  cloud_firestore: any
  firebase_core: any
  firebase_storage: any
  firebase: any
  # others
  flutter_switch: any
  universal_io: ^2.0.4
  # printing: any
  # esc_pos_utils: ^1.0.0
  #audioplayers: any



  # user intergace
  cupertino_icons: ^1.0.0
  ars_dialog: ^1.0.7
  flutter_admin_scaffold: ^1.0.0
  chips_choice: ^2.0.1
  just_audio: any
  #just_audio_background: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
